spring.application.name=USER-SERVICE
server.port=9090

#spring.datasource.url=jdbc:postgresql://localhost:5432/db_user
spring.datasource.url=jdbc:postgresql://localhost:5433/db_user
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=saha
server.servlet.context-path=/user-app/api/v1/
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.instance.metadata-map.context-path=${server.servlet.context-path}
eureka.instance.hostname=localhost
logging.level.org.springframework.web=DEBUG