spring.application.name=TASK-SERVICE
# Send db pass and username from terminal
server.port=8089
spring.datasource.url=jdbc:postgresql://localhost:5433/db_tasks
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=postgres
spring.datasource.password=saha
server.servlet.context-path=/task-app/api
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
eureka.instance.metadata-map.context-path=${server.servlet.context-path}
eureka.instance.hostname=localhost